# Generated by Django 3.2.8 on 2021-11-06 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.RenameField(
            model_name='features',
            old_name='nome',
            new_name='feature',
        ),
    ]
